In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df=sns.load_dataset('taxis')

In [3]:
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [4]:
df[['pickup_borough']].unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [5]:
unique_1=df[['pickup_borough']].drop_duplicates()

In [6]:
unique_1

    pickup_borough
0        Manhattan
10          Queens
42             NaN
92           Bronx
114       Brooklyn

In [7]:
unique_2=df['pickup_borough'].unique()
unique_2

<StringArray>
['Manhattan', 'Queens', nan, 'Bronx', 'Brooklyn']
Length: 5, dtype: str

* `df['pickup_borough'].unique()` → returns unique values as a **NumPy array**. Fast and simple.
* `df[['pickup_borough']].drop_duplicates()` → returns unique rows as a **DataFrame**, preserving index and column structure.

Use:

* `.unique()` for quick value lists
* `.drop_duplicates()` for DataFrame/table operations

In [8]:
g1=df.groupby('pickup_borough').size()
# groupby('pickup_borough') → creates groups based on borough names.
# size() → counts rows in each group.

type(g1)
g1

pickup_borough
Bronx          99
Brooklyn      383
Manhattan    5268
Queens        657
dtype: int64

In [9]:
g2=df.groupby('pickup_borough')[['pickup_borough']].count()

type(g2)
g2

                pickup_borough
pickup_borough
Bronx                       99
Brooklyn                   383
Manhattan                 5268
Queens                     657

In [10]:
help(df.groupby)

Help on method groupby in module pandas.core.frame:

groupby(
    by=None,
    level: IndexLabel | None = None,
    *,
    as_index: bool = True,
    sort: bool = True,
    group_keys: bool = True,
    observed: bool = True,
    dropna: bool = True
) -> DataFrameGroupBy method of pandas.DataFrame instance
    Group DataFrame using a mapper or by a Series of columns.

    A groupby operation involves some combination of splitting the
    object, applying a function, and combining the results. This can be
    used to group large amounts of data and compute operations on these
    groups.

    Parameters
    ----------
    by : mapping, function, label, pd.Grouper or list of such
        Used to determine the groups for the groupby.
        If ``by`` is a function, it's called on each value of the object's
        index. If a dict or Series is passed, the Series or dict VALUES
        will be used to determine the groups (the Series' values are first
        aligned; see ``.align()`` method). If a list or ndarray of length
        equal to the number of rows is passed (see the `groupby user guide
        <https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#splitting-an-object-into-groups>`_),
        the values are used as-is to determine the groups. A label or list
        of labels may be passed to group by the columns in ``self``.
        Notice that a tuple is interpreted as a (single) key.
    level : int, level name, or sequence of such, default None
        If the axis is a MultiIndex (hierarchical), group by a particular
        level or levels. Do not specify both ``by`` and ``level``.
    as_index : bool, default True
        Return object with group labels as the
        index. Only relevant for DataFrame input. as_index=False is
        effectively "SQL-style" grouped output. This argument has no effect
        on filtrations (see the `filtrations in the user guide
        <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#filtration>`_),
        such as ``head()``, ``tail()``, ``nth()`` and in transformations
        (see the `transformations in the user guide
        <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#transformation>`_).
    sort : bool, default True
        Sort group keys. Get better performance by turning this off.
        Note this does not influence the order of observations within each
        group. Groupby preserves the order of rows within each group. If False,
        the groups will appear in the same order as they did in the original
        DataFrame.
        This argument has no effect on filtrations (see the `filtrations
        in the user guide
        <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#filtration>`_),
        such as ``head()``, ``tail()``, ``nth()`` and in transformations
        (see the `transformations in the user guide
        <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#transformation>`_).

        .. versionchanged:: 2.0.0

            Specifying ``sort=False`` with an ordered categorical grouper will no
            longer sort the values.

    group_keys : bool, default True
        When calling apply and the ``by`` argument produces a like-indexed
        (i.e. :ref:`a transform <groupby.transform>`) result, add group keys to
        index to identify pieces. By default group keys are not included
        when the result's index (and column) labels match the inputs, and
        are included otherwise.

        .. versionchanged:: 2.0.0

           ``group_keys`` now defaults to ``True``.

    observed : bool, default True
        This only applies if any of the groupers are Categoricals.
        If True: only show observed values for categorical groupers.
        If False: show all values for categorical groupers.

        .. versionchanged:: 3.0.0

            The default value is now ``True``.

    dropna : bool, default True
        If True, and if group keys contain NA values, NA values together
        with row/column will be dropped.
        If False, NA values will also be treated as the key in groups.

    Returns
    -------
    pandas.api.typing.DataFrameGroupBy
        Returns a groupby object that contains information about the groups.

    See Also
    --------
    resample : Convenience method for frequency conversion and resampling
        of time series.

    Notes
    -----
    See the `user guide
    <https://pandas.pydata.org/pandas-docs/stable/groupby.html>`__ for more
    detailed usage and examples, including splitting an object into groups,
    iterating through groups, selecting a group, aggregation, and more.

    The implementation of groupby is hash-based, meaning in particular that
    objects that compare as equal will be considered to be in the same group.
    An exception to this is that pandas has special handling of NA values:
    any NA values will be collapsed to a single group, regardless of how
    they compare. See the user guide linked above for more details.

    Examples
    --------
    >>> df = pd.DataFrame(
    ...     {
    ...         "Animal": ["Falcon", "Falcon", "Parrot", "Parrot"],
    ...         "Max Speed": [380.0, 370.0, 24.0, 26.0],
    ...     }
    ... )
    >>> df
       Animal  Max Speed
    0  Falcon      380.0
    1  Falcon      370.0
    2  Parrot       24.0
    3  Parrot       26.0
    >>> df.groupby(["Animal"]).mean()
            Max Speed
    Animal
    Falcon      375.0
    Parrot       25.0

    **Hierarchical Indexes**

    We can groupby different levels of a hierarchical index
    using the `level` parameter:

    >>> arrays = [
    ...     ["Falcon", "Falcon", "Parrot", "Parrot"],
    ...     ["Captive", "Wild", "Captive", "Wild"],
    ... ]
    >>> index = pd.MultiIndex.from_arrays(arrays, names=("Animal", "Type"))
    >>> df = pd.DataFrame({"Max Speed": [390.0, 350.0, 30.0, 20.0]}, index=index)
    >>> df
                    Max Speed
    Animal Type
    Falcon Captive      390.0
           Wild         350.0
    Parrot Captive       30.0
           Wild          20.0
    >>> df.groupby(level=0).mean()
            Max Speed
    Animal
    Falcon      370.0
    Parrot       25.0
    >>> df.groupby(level="Type").mean()
             Max Speed
    Type
    Captive      210.0
    Wild         185.0

    We can also choose to include NA in group keys or not by setting
    `dropna` parameter, the default setting is `True`.

    >>> arr = [[1, 2, 3], [1, None, 4], [2, 1, 3], [1, 2, 2]]
    >>> df = pd.DataFrame(arr, columns=["a", "b", "c"])

    >>> df.groupby(by=["b"]).sum()
        a   c
    b
    1.0 2   3
    2.0 2   5

    >>> df.groupby(by=["b"], dropna=False).sum()
        a   c
    b
    1.0 2   3
    2.0 2   5
    NaN 1   4

    >>> arr = [["a", 12, 12], [None, 12.3, 33.0], ["b", 12.3, 123], ["a", 1, 1]]
    >>> df = pd.DataFrame(arr, columns=["a", "b", "c"])

    >>> df.groupby(by="a").sum()
        b     c
    a
    a   13.0   13.0
    b   12.3  123.0

    >>> df.groupby(by="a", dropna=False).sum()
        b     c
    a
    a   13.0   13.0
    b   12.3  123.0
    NaN 12.3   33.0

    When using ``.apply()``, use ``group_keys`` to include or exclude the
    group keys. The ``group_keys`` argument defaults to ``True`` (include).

    >>> df = pd.DataFrame(
    ...     {
    ...         "Animal": ["Falcon", "Falcon", "Parrot", "Parrot"],
    ...         "Max Speed": [380.0, 370.0, 24.0, 26.0],
    ...     }
    ... )
    >>> df.groupby("Animal", group_keys=True)[["Max Speed"]].apply(lambda x: x)
              Max Speed
    Animal
    Falcon 0      380.0
           1      370.0
    Parrot 2       24.0
           3       26.0

    >>> df.groupby("Animal", group_keys=False)[["Max Speed"]].apply(lambda x: x)
       Max Speed
    0      380.0
    1      370.0
    2       24.0
    3       26.0

In [11]:
g3 = df.groupby('pickup_borough')
print(type(g3))
g3.groups

'''
Why groups useful?

To know which rows belong to each category
To manually access grouped rows
For debugging and understanding groupby
For custom operations on specific groups 

groupby() creates groups
.groups shows the row-index mapping of those groups
'''

<class 'pandas.api.typing.DataFrameGroupBy'>

'\nWhy groups useful?\n\nTo know which rows belong to each category\nTo manually access grouped rows\nFor debugging and understanding groupby\nFor custom operations on specific groups \n\ngroupby() creates groups\n.groups shows the row-index mapping of those groups\n'

Because `g3`, `g2`, and `g1` are **different types of objects**.

### 1. `g3`

```python id="g1a2bc"
g3 = df.groupby('pickup_borough')
type(g3)
```

`g3` is a **GroupBy object**.

Type:

```python id="h3d4ef"
pandas.core.groupby.generic.DataFrameGroupBy
```

A `GroupBy` object stores:

* the groups
* indexes
* grouping logic

So it has attributes like:

```python id="j5k6lm"
g3.groups
```

---

### 2. `g2`

```python id="n7p8qr"
g2 = df.groupby('pickup_borough')[['pickup_borough']].count()
```

Here, `.count()` is already executed.

So `g2` becomes a normal **DataFrame**.

Type:

```python id="s1t2uv"
pandas.core.frame.DataFrame
```

DataFrames do NOT have `.groups`.

---

### 3. `g1`

```python id="w3x4yz"
g1 = df.groupby('pickup_borough').size()
```

`.size()` returns counts directly.

So `g1` becomes a **Series**.

Type:

```python id="a5b6cd"
pandas.core.series.Series
```

Series also do NOT have `.groups`.

---

### Simple rule

| Variable | Type           | Has `.groups`? |
| -------- | -------------- | -------------- |
| `g3`     | GroupBy object | ✅ Yes          |
| `g2`     | DataFrame      | ❌ No           |
| `g1`     | Series         | ❌ No           |

`.groups` exists only before aggregation (`count()`, `size()`, `sum()`, etc.) is applied.

In [12]:
g3.get_group('Manhattan').head()
# get_group() returns all rows belonging to a specific group.

'''.groups → gives row indexes
.get_group() → gives actual rows/data of that group'''

print(g3.groups.keys())
# .groups.keys() lists all unique group names (categories) in the grouping column.

dict_keys(['Bronx', 'Brooklyn', 'Manhattan', 'Queens'])

In [13]:

print(g3.groups['Manhattan'][:5])
# .groups['Manhattan'] gives row indexes for the 'Manhattan' group. [:5] shows the first 5 indexes.

Index([0, 1, 2, 3, 4], dtype='int64')

In [14]:
print(g3.get_group('Manhattan')[['pickup_borough']].head())
# get_group('Manhattan') returns all rows for 'Manhattan'. [['pickup_borough']] selects just that column. head() shows the first 5 rows of that selection.

  pickup_borough
0      Manhattan
1      Manhattan
2      Manhattan
3      Manhattan
4      Manhattan

In [15]:
g3.ngroups
# .ngroups gives the total number of unique groups formed. In this case, it counts how many unique pickup boroughs there are in the dataset.
print(g3.ngroups)

4

In [16]:
g3.size()

pickup_borough
Bronx          99
Brooklyn      383
Manhattan    5268
Queens        657
dtype: int64

In [17]:
for name, data in g3:
    print(name)
    print(data.head(2))
    print('---')
# Looping through groups:
# name → the group name (e.g., 'Manhattan')
# data → the DataFrame containing rows of that group
# head(2) shows the first 2 rows of each group for demonstration.

Bronx
                 pickup             dropoff  passengers  distance  fare  tip  \
92  2019-03-28 07:05:19 2019-03-28 07:41:14           0     10.60  33.5  0.0
174 2019-03-04 20:56:26 2019-03-04 21:13:36           1      9.97  28.5  0.0

     tolls  total   color      payment             pickup_zone  \
92    5.76  40.06  yellow  credit card            East Tremont
174   0.00  29.80  yellow  credit card  Mott Haven/Port Morris

                            dropoff_zone pickup_borough dropoff_borough
92                          Midtown East          Bronx       Manhattan
174  Riverdale/North Riverdale/Fieldston          Bronx           Bronx
---
Brooklyn
                 pickup             dropoff  passengers  distance  fare   tip  \
114 2019-03-05 12:17:49 2019-03-05 12:36:12           1      5.98  19.0  5.58
155 2019-03-21 22:49:32 2019-03-21 22:55:11           1      1.03   6.0  1.46

     tolls  total   color      payment         pickup_zone      dropoff_zone  \
114    0.0  27.88  yellow  credit card    Brooklyn Heights       Murray Hill
155    0.0   8.76  yellow  credit card  DUMBO/Vinegar Hill  Brooklyn Heights

    pickup_borough dropoff_borough
114       Brooklyn       Manhattan
155       Brooklyn        Brooklyn
---
Manhattan
               pickup             dropoff  passengers  distance  fare   tip  \
0 2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0  2.15
1 2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0  0.00

   tolls  total   color      payment            pickup_zone  \
0    0.0  12.95  yellow  credit card        Lenox Hill West
1    0.0   9.30  yellow         cash  Upper West Side South

            dropoff_zone pickup_borough dropoff_borough
0    UN/Turtle Bay South      Manhattan       Manhattan
1  Upper West Side South      Manhattan       Manhattan
---
Queens
                pickup             dropoff  passengers  distance  fare   tip  \
10 2019-03-16 10:02:25 2019-03-16 10:22:29           1      3.90  17.0  0.00
22 2019-03-28 17:20:54 2019-03-28 17:55:57           1      9.82  31.5  8.31

    tolls  total   color      payment        pickup_zone  \
10   0.00  17.80  yellow         cash  LaGuardia Airport
22   5.76  49.87  yellow  credit card  LaGuardia Airport

                     dropoff_zone pickup_borough dropoff_borough
10                        Astoria         Queens          Queens
22  Sutton Place/Turtle Bay North         Queens       Manhattan
---

A `GroupBy` object can be iterated in different ways.

Example:

```python id="m4q8tw"
g3 = df.groupby('pickup_borough')
```

---

### 1. Iterate group name + data (most common)

```python id="k7n2vx"
for name, data in g3:
    print(name)
    print(data)
```

* `name` → group name
* `data` → DataFrame of that group

---

### 2. Iterate only group names

```python id="r5p1lz"
for name in g3.groups:
    print(name)
```

Output:

```python id="x8d4qm"
Manhattan
Queens
Brooklyn
```

---

### 3. Iterate group name + row indexes

```python id="c2v7wy"
for name, indexes in g3.groups.items():
    print(name, indexes)
```

Output:

```python id="h6m3pt"
Manhattan Int64Index([0,2], dtype='int64')
Queens Int64Index([1], dtype='int64')
```

---

### 4. Iterate using `indices`

```python id="u9k5rx"
for name, indexes in g3.indices.items():
    print(name, indexes)
```

Similar to `.groups`.

---

### 5. Iterate aggregated results

```python id="a1t8mn"
for name, value in g3['fare'].sum().items():
    print(name, value)
```

Output:

```python id="e4q7zs"
Manhattan 30
Queens 15
```

---

### Important understanding

`GroupBy` iteration gives:

```python id="d5w2lp"
(group_name, grouped_dataframe)
```

# .items() is used to iterate through key-value pairs.
'''
| Method      | Returns           |
| ----------- | ----------------- |
| `.keys()`   | only keys         |
| `.values()` | only values       |
| `.items()`  | key + value pairs |
'''

So internally:

```python id="f8x6kr"
for x in g3:
```

each `x` looks like:

```python id="p3n9tv"
('Manhattan', <DataFrame>)
```

In [18]:
# df.select_dtypes(include='number').groupby(by=df['pickup_borough']).mean()
# groupby() groups by 'pickup_borough'
# select_dtypes(include='number') selects only numeric columns
# mean() calculates the average of those numeric columns for each group.

df.groupby('pickup_borough').mean(numeric_only=True)

                passengers  distance       fare       tip     tolls      total
pickup_borough
Bronx             1.191919  5.725859  20.999091  0.148586  0.778182  22.765253
Brooklyn          1.310705  4.058668  16.520836  0.966345  0.285744  19.236240
Manhattan         1.566059  2.349723  11.152889  1.939550  0.142912  16.670507
Queens            1.523592  7.465830  24.934642  3.040061  1.709833  31.660107

In [19]:
df.select_dtypes(include='number').groupby(df['pickup_borough'])[['fare']].agg(['mean', 'sum'])

                     fare
                     mean       sum
pickup_borough
Bronx           20.999091   2078.91
Brooklyn        16.520836   6327.48
Manhattan       11.152889  58753.42
Queens          24.934642  16382.06

In [20]:
import numpy as np
df.select_dtypes(include='number').groupby(df['pickup_borough'])[['fare']].agg([np.mean, np.sum])

                     fare
                     mean       sum
pickup_borough
Bronx           20.999091   2078.91
Brooklyn        16.520836   6327.48
Manhattan       11.152889  58753.42
Queens          24.934642  16382.06

In [21]:
df.groupby('pickup_borough').agg({
    'fare': [np.sum, np.mean],
    'tip': [np.std]
    })

                    fare                  tip
                     sum       mean       std
pickup_borough
Bronx            2078.91  20.999091  0.892718
Brooklyn         6327.48  16.520836  1.665033
Manhattan       58753.42  11.152889  2.023762
Queens          16382.06  24.934642  4.349021

In [22]:
df.groupby('pickup_borough')[['fare']].describe()

                  fare
                 count       mean        std  min    25%   50%     75%     max
pickup_borough
Bronx             99.0  20.999091  15.240500  2.5  10.75  16.0  30.500   81.86
Brooklyn         383.0  16.520836  13.670890  2.5   7.50  12.5  19.855   93.50
Manhattan       5268.0  11.152889   8.239970  2.5   6.00   8.5  13.000  130.00
Queens           657.0  24.934642  19.636496  1.0   8.50  21.0  36.000  150.00

In [35]:
#multi-level columns from groupby with agg() 
df.groupby(['pickup_borough','color'])[['fare', 'tip']].agg({
    'fare': [np.sum, np.mean],
    'tip': [np.std]
    })
# Here pickup_borough and color is an index, not a normal column. reset_index() converts it back to a regular column,

                           fare                  tip
                            sum       mean       std
pickup_borough color
Bronx          green    1699.03  20.470241  0.972367
               yellow    379.88  23.742500  0.000000
Brooklyn       green    5023.10  16.048243  1.606272
               yellow   1304.38  18.634000  1.873921
Manhattan      green    3111.60  10.583673  1.660236
               yellow  55641.82  11.186534  2.030853
Queens         green    3926.92  13.635139  1.250647
               yellow  12455.14  33.753767  4.933410

In [34]:
df.groupby(['pickup_borough','color'])[['fare', 'tip']].agg({
    'fare': [np.sum, np.mean],
    'tip': [np.std]
    }).reset_index()

# Here pickup_borough and color is an index, not a normal column. reset_index() converts it back to a regular column, 
# making the DataFrame easier to work with for further analysis or visualization.

  pickup_borough   color      fare                  tip
                               sum       mean       std
0          Bronx   green   1699.03  20.470241  0.972367
1          Bronx  yellow    379.88  23.742500  0.000000
2       Brooklyn   green   5023.10  16.048243  1.606272
3       Brooklyn  yellow   1304.38  18.634000  1.873921
4      Manhattan   green   3111.60  10.583673  1.660236
5      Manhattan  yellow  55641.82  11.186534  2.030853
6         Queens   green   3926.92  13.635139  1.250647
7         Queens  yellow  12455.14  33.753767  4.933410

In [36]:
# you can also reset index with as index=False in agg() instead of reset_index() at the end. It gives the same result.
df.groupby(['pickup_borough','color'], as_index=False)[['fare', 'tip']].agg({
    'fare': [np.sum, np.mean],
    'tip': [np.std]
    })

  pickup_borough   color      fare                  tip
                               sum       mean       std
0          Bronx   green   1699.03  20.470241  0.972367
1          Bronx  yellow    379.88  23.742500  0.000000
2       Brooklyn   green   5023.10  16.048243  1.606272
3       Brooklyn  yellow   1304.38  18.634000  1.873921
4      Manhattan   green   3111.60  10.583673  1.660236
5      Manhattan  yellow  55641.82  11.186534  2.030853
6         Queens   green   3926.92  13.635139  1.250647
7         Queens  yellow  12455.14  33.753767  4.933410

In [37]:
# rename agg columns with named aggregation
df.groupby(['pickup_borough','color'], as_index=False)[['fare', 'tip']].agg(
    total_fare = pd.NamedAgg(column='fare', aggfunc='sum'),
    avg_fare = pd.NamedAgg(column='fare', aggfunc='mean'),
    std_tip = pd.NamedAgg(column='tip', aggfunc='std')
    )

  pickup_borough   color  total_fare   avg_fare   std_tip
0          Bronx   green     1699.03  20.470241  0.978278
1          Bronx  yellow      379.88  23.742500  0.000000
2       Brooklyn   green     5023.10  16.048243  1.608844
3       Brooklyn  yellow     1304.38  18.634000  1.887451
4      Manhattan   green     3111.60  10.583673  1.663067
5      Manhattan  yellow    55641.82  11.186534  2.031058
6         Queens   green     3926.92  13.635139  1.252824
7         Queens  yellow    12455.14  33.753767  4.940109

In [38]:
# rename agg columns with named aggregation
df.groupby(['pickup_borough','color'], as_index=False)[['fare', 'tip']].agg(
    total_fare = ('fare','sum'),
    avg_fare = ('fare', 'mean'),
    std_tip = pd.NamedAgg(column='tip', aggfunc='std')
    )

  pickup_borough   color  total_fare   avg_fare   std_tip
0          Bronx   green     1699.03  20.470241  0.978278
1          Bronx  yellow      379.88  23.742500  0.000000
2       Brooklyn   green     5023.10  16.048243  1.608844
3       Brooklyn  yellow     1304.38  18.634000  1.887451
4      Manhattan   green     3111.60  10.583673  1.663067
5      Manhattan  yellow    55641.82  11.186534  2.031058
6         Queens   green     3926.92  13.635139  1.252824
7         Queens  yellow    12455.14  33.753767  4.940109

In [39]:
#.appluy method allows you to apply a custom function to each group. 
# You can define your own function and use it with apply() to perform complex operations on the grouped data. For example:

In [44]:
def median_fare(group):
    f_median =group[['fare','tip']].median()
    return f_median

In [45]:
df.groupby('pickup_borough').apply(median_fare)

                fare   tip
pickup_borough
Bronx           16.0  0.00
Brooklyn        12.5  0.00
Manhattan        8.5  1.86
Queens          21.0  0.00

`agg()` and `apply()` are both used with `groupby()`, but they are different.

---

# `.agg()`

Used for **aggregation**:

* sum
* mean
* min
* max
* count

Returns summarized values.

Example:

```python id="a4m8pk"
df.groupby('pickup_borough')['fare_amount'].agg('mean')
```

Output:

* one mean value per group

---

# `.apply()`

Used for **custom operations** on each group.

You can run your own function.

Example:

```python id="k7q2tw"
df.groupby('pickup_borough').apply(lambda x: x.head(2))
```

Returns first 2 rows from each group.

---

# Main difference

| `.agg()`                  | `.apply()`          |
| ------------------------- | ------------------- |
| Fast                      | Slower              |
| For summaries             | For custom logic    |
| Returns aggregated values | Can return anything |
| Simple operations         | Flexible operations |

---

Example:

### `agg`

```python id="n5p1vx"
df.groupby('pickup_borough').agg({
    'fare_amount': 'sum',
    'tip_amount': 'mean'
})
```

---

### `apply`

```python id="r8d4qm"
df.groupby('pickup_borough').apply(
    lambda g: g[g['fare_amount'] > 20]
)
```

Returns filtered rows inside each group.

---

Rule:

* Use `.agg()` for calculations/summaries
* Use `.apply()` for custom group processing

# TRANSFORM METHOD


transform() is used when you want to:

perform a group-wise calculation
but keep the same number of rows as the original DataFrame

Unlike agg(), it does NOT reduce rows.

returns same aggregated value in every row of the data frame without reducing the rows

In [77]:
# Get numeric column names
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()

# Group by borough and calculate mean for numeric columns
result = df.groupby(['pickup_borough','color'])[numeric_cols].transform('mean').reset_index()

In [78]:
result.head()

   index  passengers  distance       fare       tip    tolls      total
0      0    1.591074   2.35153  11.186534  1.992589  0.14388  16.865394
1      1    1.591074   2.35153  11.186534  1.992589  0.14388  16.865394
2      2    1.591074   2.35153  11.186534  1.992589  0.14388  16.865394
3      3    1.591074   2.35153  11.186534  1.992589  0.14388  16.865394
4      4    1.591074   2.35153  11.186534  1.992589  0.14388  16.865394

In [81]:
# Group by borough and calculate mean for numeric columns
df['avg_fare'] = df.groupby(['pickup_borough','color'])[['fare']].transform('mean')

In [82]:
df.columns

Index(['pickup', 'dropoff', 'passengers', 'distance', 'fare', 'tip', 'tolls',
       'total', 'color', 'payment', 'pickup_zone', 'dropoff_zone',
       'pickup_borough', 'dropoff_borough', 'avg_fare'],
      dtype='str')

In [89]:
df[['pickup_borough', 'avg_fare']].drop_duplicates()

     pickup_borough   avg_fare
0         Manhattan  11.186534
10           Queens  33.753767
42              NaN        NaN
92            Bronx  23.742500
114        Brooklyn  18.634000
5451         Queens  13.635139
5453      Manhattan  10.583673
5455       Brooklyn  16.048243
5457          Bronx  20.470241

In [93]:
# filter groups with filter() method
# filter groups based on a condition. For example, to keep only groups with an average fare greater than 10:
def filter_high_avg_fare(group):
    avg_fare = group['fare'].mean()
    return avg_fare > 20

In [95]:
df.groupby('pickup_borough').filter(filter_high_avg_fare)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough,avg_fare
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.00,0.00,17.80,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens,33.753767
22,2019-03-28 17:20:54,2019-03-28 17:55:57,1,9.82,31.5,8.31,5.76,49.87,yellow,credit card,LaGuardia Airport,Sutton Place/Turtle Bay North,Queens,Manhattan,33.753767
43,2019-03-27 19:39:16,2019-03-27 20:00:26,1,9.50,28.0,0.00,5.76,35.06,yellow,cash,LaGuardia Airport,Washington Heights South,Queens,Manhattan,33.753767
53,2019-03-20 18:49:24,2019-03-20 19:12:40,1,13.45,36.0,0.00,0.00,37.80,yellow,cash,JFK Airport,Sunnyside,Queens,Queens,33.753767
56,2019-03-05 17:57:00,2019-03-05 18:45:25,2,19.59,52.0,0.00,5.76,65.56,yellow,credit card,JFK Airport,Upper East Side North,Queens,Manhattan,33.753767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6417,2019-03-10 12:10:45,2019-03-10 12:43:05,2,11.17,35.0,0.00,5.76,41.56,green,credit card,Hillcrest/Pomonok,Flatiron,Queens,Manhattan,13.635139
6418,2019-03-02 21:47:50,2019-03-02 21:55:34,1,1.48,7.5,1.76,0.00,10.56,green,credit card,Forest Hills,Kew Gardens Hills,Queens,Queens,13.635139
6423,2019-03-12 08:10:47,2019-03-12 08:35:35,1,4.30,18.5,0.00,0.00,19.30,green,credit card,Saint Albans,Hillcrest/Pomonok,Queens,Queens,13.635139
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.0,0.00,0.00,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan,20.470241
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.00,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx,13.635139

In [98]:
df.groupby('pickup_borough').filter(lambda g: g['fare'].mean() > 20)

'''
Together in groupby

filter() needs a function that:

receives each group
returns True/False

lambda is commonly used for quick conditions.

'''

'\nTogether in groupby\n\nfilter() needs a function that:\n\nreceives each group\nreturns True/False\n\nlambda is commonly used for quick conditions.\n\n'